Ms 15 delete project
opinionatedOtter/lf8_management_service pull request #7
Opened 2022-11-10 21:32 UTC by Y0-L0

2022-11-11 08:51 UTC, jcpwdev reviewed
ich wäre dafür den anderen MR zuerst zu mergen, damit der diff eindeutiger ist.

dann würde ich mir das erneut angucken :+1:

2022-11-12 20:29 UTC, opinionatedOtter requested changes

2022-11-12 20:29 UTC, opinionatedOtter commented on src/main/java/de/szut/lf8_project/application/ProjectApplicationService.java
> +            return;
Das kann weg. Die Methode terminiert automatisch, wenn es keine Instruktionen mehr gibt.

2022-11-12 20:29 UTC, opinionatedOtter commented on src/test/java/de/szut/lf8_project/integration/TestDeleteProject.java
> +                .andExpect(status().isOk());
Komische Formatierung :thinking: 
Wir sollten außerdem eig. danach noch testen, dass das Projekt auch wirklich gelöscht ist.

2022-11-12 20:29 UTC, opinionatedOtter commented on src/test/java/de/szut/lf8_project/integration/TestDeleteProject.java
> +        ResultActions result = mockMvc.perform(get("/api/v1/project/99999999")
Get?

2022-11-12 20:29 UTC, opinionatedOtter commented on src/test/java/de/szut/lf8_project/integration/TestDeleteProject.java
> +        ResultActions result = mockMvc.perform(get("/api/v1/project/xyz")
Get?

2022-11-12 20:29 UTC, opinionatedOtter commented on src/test/java/de/szut/lf8_project/integration/TestDeleteProject.java
> +        ResultActions result = mockMvc.perform(get("/api/v1/project/1")
Get it? :drum:

2022-11-14 18:05 UTC, jcpwdev approved these changes

2022-11-14 18:05 UTC, jcpwdev commented on src/main/java/de/szut/lf8_project/domain/adapter/OpenApiProjectController.java
> +    @Operation(summary = "Delete a Project by it's ID")
```suggestion
    @Operation(summary = "Delete a project by it's ID")
```

2022-11-14 18:05 UTC, jcpwdev commented on src/main/java/de/szut/lf8_project/domain/adapter/OpenApiProjectController.java
> +                    description = "The Project was successfully deleted",
```suggestion
                    description = "The project was successfully deleted",
```

2022-11-14 18:05 UTC, jcpwdev commented on src/test/java/de/szut/lf8_project/integration/TestDeleteProject.java
> +                .andExpect(jsonPath("$").doesNotExist());
gibts hier nicht was expliziteres wie content().doesNotExist() oder content().isEmpty()?

2022-11-14 18:05 UTC, jcpwdev commented on src/test/java/de/szut/lf8_project/integration/TestDeleteProject.java
> +
```suggestion
```

2022-11-15 13:19 UTC, opinionatedOtter approved these changes

2022-11-16 08:27 UTC, closed without merging