Ms 12 get all projects
opinionatedOtter/lf8_management_service pull request #8
Opened 2022-11-10 21:34 UTC by Y0-L0

2022-11-11 08:47 UTC, jcpwdev reviewed
eig nur was in den tests

2022-11-11 08:47 UTC, jcpwdev commented on src/test/java/de/szut/lf8_project/integration/TestGetAllProjects.java
> +        ResultActions result = mockMvc.perform(get("/api/v1/project/1")
Falsche Route

2022-11-11 08:47 UTC, jcpwdev commented on src/test/java/de/szut/lf8_project/integration/TestGetAllProjects.java
> +        ResultActions result = mockMvc.perform(get("/api/v1/project/xyz")
Falsche Route - und ich glaube wenn du das fixt, geht der test flöten :D

2022-11-11 08:47 UTC, jcpwdev commented on src/test/java/de/szut/lf8_project/integration/TestGetAllProjects.java
> +    @DisplayName("sollte erfolgreich ein Projekt löschen")
ich hoffe das tut sie nicht :D:D

2022-11-11 08:47 UTC, jcpwdev commented on src/test/java/de/szut/lf8_project/integration/TestGetAllProjects.java
> +        // Project project = createProjectInDatabase();
lösch mich und ändere meinen func namen :D

2022-11-11 13:33 UTC, opinionatedOtter requested changes
Siehe Johanns Kommentare. Hab sonst nichts

2022-11-11 13:33 UTC, opinionatedOtter commented on http-client.private.env.json
> +}
good call :+1:

2022-11-11 13:42 UTC, jcpwdev commented
glaube die OpenApi Dokumentation fehlt noch? oder hab ich die übersehen?

2022-11-13 08:20 UTC, Y0-L0 commented on src/test/java/de/szut/lf8_project/integration/TestGetAllProjects.java
> +        ResultActions result = mockMvc.perform(get("/api/v1/project/xyz")
wenn ich das fixe ist der Rest redundant, weil ich keine Infos wie eine ID oder ähnliches abschicken muss. Test deleted

2022-11-13 08:20 UTC, Y0-L0 commented on src/test/java/de/szut/lf8_project/integration/TestGetAllProjects.java
> +    @DisplayName("sollte erfolgreich ein Projekt löschen")
yup, copy-paste fehler

2022-11-13 08:22 UTC, Y0-L0 commented on http-client.private.env.json
> +}
Ich habs leider noch nicht geschafft, dass er den Response direkt als environment variable abspeichert. Das geht nämlich eigentlich auch :cry: 

https://www.jetbrains.com/help/idea/http-response-handling-examples.html#script-var-example

2022-11-13 09:30 UTC, jcpwdev approved these changes

2022-11-13 09:30 UTC, merged