Integrationstests für MS-16 (Add Employee)
opinionatedOtter/lf8_management_service pull request #9
Opened 2022-11-11 10:46 UTC by jcpwdev

Die Pipeline/Tests sind bewusst nicht alle grün, folgendes to be discussed:

1. Im Erfolgsfall 'Created' statt 'OK' zurückgeben
2. Bei unpassender 'ProjectRole' in der 'ErrorDetails' einen (neuen) besseren Titel als 'INVALID_PARAMETER' zurückgeben
3. Ein Test funktioniert nicht (und ist vorerst deaktiviert), da sich die Employee-API nicht richtig verhält - die scheint keine Rollen auf Employees zu updaten, wenn man einen Employee dort updatet.

2022-11-12 21:01 UTC, opinionatedOtter requested changes
OpenApi eben fix nachziehen und morgen den Test besprechen.
Sieht ansonsten gut aus :+1: 
Rest ist eher Optional.

2022-11-12 21:01 UTC, opinionatedOtter commented on src/main/java/de/szut/lf8_project/domain/adapter/OpenApiProjectController.java
>                      description = "You do not have the required user permissions for this action.",
bei 400?
401er scheint dafür zu fehlen.

2022-11-12 21:01 UTC, opinionatedOtter commented on src/test/java/de/szut/lf8_project/FullIntegrationTest.java
> +        TransferProjectRole transfer = transferProjectRoleResponseEntity.getBody();
Suggestion:
Ich kann mit "Transfer" irgendwie nicht viel anfangen.
Ich verstehe zwar was es tut, aber das Naming finde ich etwas suboptimal.

2022-11-12 21:01 UTC, opinionatedOtter commented on src/test/java/de/szut/lf8_project/integration/TestAddEmployeeToProject.java
> +                .andExpect(status().isCreated());
To Discuss:
Ähnlich wie bei Johannes frage ich mich hier, ob man nicht eig. noch die DB fragen müsste, ob die Entity wirklich geupdated wurde.
Ist ja eig. auch Teil der Integration.

2022-11-12 21:01 UTC, opinionatedOtter commented on src/test/java/de/szut/lf8_project/integration/TestAddEmployeeToProject.java
> +            Project collidingProject = createProjectInDatabase();
Ich fänds super, wenn wir hier sowas wie ```createDefaultProjectInDatabaseWithTeamMember``` und ```createDefaultProject``` als Naming hätten.
Oder eben so etwas in der Art.
Macht es etwas klarer, dass das scheinbar das selbe Projekt ist (außer ID) und Sie daher kollidieren.
Finde ich etwas besser, als einfach dem Variablen Namen zu vertrauen.

Wovon ist sonst auch nen Fan für nächste mal bin, wäre einfach eine create-Methode zu haben, der ein Default-Projekt übergeben wird, welches die entsprechende Test-Klasse aber selbst in Ihrem Klassen-Scope deklariert.
Wenn der Test dann eine Mutation der Entity benötigt, kann man das im Test machen oder einfach nochmal die relevanten Werte explizit setzen, um den Test noch deutlicher zu machen.
Auch kann ich dann die Default-Entity direkt in der Klasse sehen und muss ich in die Helper-Methoden einer anderen Klasse springen.
Passt so aber auch :+1:

2022-11-12 21:01 UTC, opinionatedOtter commented on src/test/java/de/szut/lf8_project/integration/TestAddEmployeeToProject.java
> +                    .andExpect(jsonPath("$.teamMember[0].employeeId", is(employeeId.unbox().intValue())))
Mh ok, daher hatte Johannes diese Art der Formatierung.
Gut, bin ich sonst auch fine mit.

2022-11-12 21:01 UTC, opinionatedOtter commented on src/test/java/de/szut/lf8_project/integration/TestAddEmployeeToProject.java
> +        void updateDifferentRole() throws Exception {
Das einfachste wäre hier sonst wohl dem Employee einfach von Anfang an 2 Rollen zu geben.
Außer wir waren einfach zu blöd für die API, aber das bezweifle ich einfach mal.

2022-11-12 21:43 UTC, jcpwdev commented on src/test/java/de/szut/lf8_project/integration/TestAddEmployeeToProject.java
> +                    .andExpect(jsonPath("$.teamMember[0].employeeId", is(employeeId.unbox().intValue())))
ne ist schon richtig, kann bei onliner assertions weg

2022-11-12 21:44 UTC, jcpwdev commented on src/test/java/de/szut/lf8_project/integration/TestAddEmployeeToProject.java
> +                .andExpect(status().isCreated());
ja, auf jeden fall, gute idee

2022-11-13 00:27 UTC, jcpwdev commented on src/main/java/de/szut/lf8_project/domain/adapter/OpenApiProjectController.java
>                      description = "You do not have the required user permissions for this action.",
verstehe grade net, was du da meinst

2022-11-13 00:34 UTC, jcpwdev commented on src/test/java/de/szut/lf8_project/FullIntegrationTest.java
> +        TransferProjectRole transfer = transferProjectRoleResponseEntity.getBody();
Wrapper...? AnnotationHolder? :D

2022-11-13 08:43 UTC, Y0-L0 commented on src/test/java/de/szut/lf8_project/FullIntegrationTest.java
> +        TransferProjectRole transfer = transferProjectRoleResponseEntity.getBody();
suboptional :laughing:

2022-11-13 08:56 UTC, jcpwdev commented on src/test/java/de/szut/lf8_project/integration/TestAddEmployeeToProject.java
> +            Project collidingProject = createProjectInDatabase();
habs zu vorschlag 2 umgewandelt.

es gibt nun 2 dinge:
- "create" Methoden - erstellen einfach nur entitäten, ähnlich wie Builder
- "save" methoden - speichern die erstellten entitäten

1-2 crossovers im inne von "createAndSave..." gibt es, weil sonst unnötige schreibarbeit.

2022-11-13 09:02 UTC, jcpwdev commented on src/test/java/de/szut/lf8_project/integration/TestAddEmployeeToProject.java
> +        void updateDifferentRole() throws Exception {
done

2022-11-13 09:25 UTC, opinionatedOtter commented on src/main/java/de/szut/lf8_project/domain/adapter/OpenApiProjectController.java
>                      description = "You do not have the required user permissions for this action.",
Nvm github hatte das eingeklappt

2022-11-13 10:31 UTC, Y0-L0 approved these changes

2022-11-13 11:03 UTC, opinionatedOtter approved these changes

2022-11-13 11:19 UTC, merged